### ISSUE TITLE
xva-img --version (incorrect version)

### ISSUE THREAD

**Issue by fvcr** [eriklax/xva-img#11]
Hi @eriklax,
the --version parameter does not reflect the version of xva-img, but that of the compiler.

![1](https://user-images.githubusercontent.com/59065937/110185752-1ced8400-7e0b-11eb-8a26-79b76e7ffecb.png)

**Comment by eriklax** [comment]
Thanks, version macros were named ``__VERSION__`` vs ``_VERSION_``

**Comment by eriklax** [comment]
Fixed with https://github.com/eriklax/xva-img/commit/3c359f3ab6e3728b1f2cf6af30b54f64e47dbec0
