### ISSUE TITLE
fatal error: xxhash.h

### ISSUE THREAD

**Issue by rbucurica** [eriklax/xva-img#14]
When running make install I get the error:

Scanning dependencies of target xva-img
[ 11%] Building CXX object CMakeFiles/xva-img.dir/src/disk.cpp.o
[ 22%] Building CXX object CMakeFiles/xva-img.dir/src/main.cpp.o
[ 33%] Building CXX object CMakeFiles/xva-img.dir/src/package.cpp.o
[ 44%] Building CXX object CMakeFiles/xva-img.dir/src/progress.cpp.o
[ 55%] Building CXX object CMakeFiles/xva-img.dir/src/readfile.cpp.o
[ 66%] Building CXX object CMakeFiles/xva-img.dir/src/sha1.cpp.o
[ 77%] Building CXX object CMakeFiles/xva-img.dir/src/writefile.cpp.o
[ 88%] Building CXX object CMakeFiles/xva-img.dir/src/xxh64.cpp.o
/home/user/xva-img/src/xxh64.cpp:34:10: fatal error: xxhash.h: No such file or directory
 #include <xxhash.h>
          ^~~~~~~~~~
compilation terminated.
CMakeFiles/xva-img.dir/build.make:230: recipe for target 'CMakeFiles/xva-img.dir/src/xxh64.cpp.o' failed
make[2]: *** [CMakeFiles/xva-img.dir/src/xxh64.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xva-img.dir/all' failed
make[1]: *** [CMakeFiles/xva-img.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eriklax** [comment]
You need to install libxxhash-dev or similar depending on your Linux disto

**Comment by rbucurica** [comment]
Worked with libxxhash-dev.
Thank you!
