### ISSUE TITLE
Please don't hardcode /usr/local/bin/ into CMakeLists.txt

### ISSUE THREAD

**Issue by xtaran** [eriklax/xva-img#4]
I don't know how this is done with CMake, but I'm sure there are some standard methods to derive the correct directory from some defaults plus environment or commandline options with CMake, too.

Actually, if I want to install it into `/usr/bin/` instead of `/usr/local/bin/`, the common way to achieve this with CMake is to pass `-DCMAKE_INSTALL_PREFIX=/usr` on the commandline. But with xva-img, this setting is completely ignored.

**Comment by eriklax** [comment]
Thanks for the feedback, I've changed to a relative path 58454de7193a15f1171c95ca2dd28a99a629b10d
