### ISSUE TITLE
Please grant a license exemption for linking xva-img against OpenSSL

### ISSUE THREAD

**Issue by xtaran** [eriklax/xva-img#5]
I'm currently looking into packaging xva-img for Debian, see https://bugs.debian.org/854490.

Your code is under GPL and the GPL is incompatible with some terms of the OpenSSL license. This makes Debian (and probably other distributions, too) not allowing GPL-licensed code to be linked with OpenSSL libraries unless there is a license exception explicitly permitting this.

To grant such an exception, it should suffice to add these paragraphs to whereever the GPL preamble is used (and probably also to the LICENSE file):

>  In addition, as a special exception, the copyright holders give permission to link the code of portions of this program with the OpenSSL library under certain conditions as described in each individual source file, and distribute linked combinations including the two.
>
> You must obey the GNU General Public License in all respects for all of the code used other than OpenSSL. If you modify file(s) with this exception, you may extend this exception to your version of the file(s), but you are not obligated to do so. If you do not wish to do so, delete this exception statement from your version. If you delete this exception statement from all source files in the program, then also delete it here.

Alternatively (but surely more effort) would be to also support GnuTLS as alternative to OpenSSL.

**Comment by eriklax** [comment]
No problem, I happily grant such exemption. a6c39ac63b77822013804b9b5756b99f7f39d9d8 3ac3618182d8d72272296b3a02f6929ffd1b1fcb

**Comment by xtaran** [comment]
Thanks!

**Comment by fr4ncisco** [comment]
https://github.com/eriklax/xva-img/archive/1.4.tar.gz

**Comment by eriklax** [comment]
1.4.1 is out with the exemption
