### ISSUE TITLE
XVAs now use xxhash instead of sha1 checksums

### ISSUE THREAD

**Issue by phaenyx** [eriklax/xva-img#8]
XVA files exported from XenServer and XCP-ng now use xxhash. Exporting fails to find .checksum files.

**Comment by dsiminiuk** [comment]
I ran into this issue also.

```
Exporting: |                                                     | ERROR
xva-img: unable to read 00000000.checksum
```

**Comment by mmorier86** [comment]
Same problem here trying to migrate a VM from Xen 8.1 to PVE
Anybody able to add some code to the project to support xxhash and not just SHA1 ( .checksum file ) ?

**Comment by mmorier86** [comment]
https://docs.citrix.com/en-us/citrix-hypervisor/vms/import-export.html
"  If the VM was exported from Citrix Hypervisor 8.0 or earlier, this file has the extension .checksum. If the VM was exported from Citrix Hypervisor 8.1 or later, this file has the extension .xxhash. " 

Part of this projet could be use in this project to support it ?!
https://github.com/Cyan4973/xxHash

**Comment by mmorier86** [comment]
Finally what I have done is shouting down my XEN 8.1 VM ( a CentOS one ) and export it from XenCenter as OVA/OVF to have the VHD file that can be import in most other Hypervisor directly.

**Comment by linrock** [comment]
i've added support for `xxhash` checksums in the linked PR. it supports both `*.checksum` files and `*.xxhash` files.

you can apply this patch on top of the latest `xva-img` version to add xxhash support:
https://patch-diff.githubusercontent.com/raw/eriklax/xva-img/pull/12.diff

it will require the xxhash development headers to compile: `sudo apt install libxxhash-dev`
